(function(){
  const config=window.DRS_CONFIG||{},live=config.mode==='production',base=String(config.apiBase||'').replace(/\/$/,'');
  async function request(path,options={}){const response=await fetch(base+path,{credentials:'include',headers:{'content-type':'application/json','idempotency-key':crypto.randomUUID(),...(options.headers||{})},...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(humanError(data.error,data));return data;}
  const post=(path,body)=>request(path,{method:'POST',body:JSON.stringify(body)});
  async function persist(kind,data,page){
    if(!live)return null;
    const routes={
      income:()=>post('/api/income',{date:data.date,source:data.source,description:data.description,amount:data.amount}),
      'add-funds':()=>post('/api/funds/direct',{date:data.date,category:page,source:data.source,note:data.note,amount:data.amount}),
      expense:()=>post('/api/expenses',{date:data.date,category:'living',planId:data.budgetId,description:data.description,amount:data.amount}),
      'pay-bill':()=>post('/api/expenses',{date:data.date,category:'living',planId:data.id,expenseType:'bill',description:'Bill payment',amount:data.amount}),
      'allocate-goal':()=>post('/api/goals/allocate',{date:data.date,goalId:data.id,amount:data.amount}),
      'use-funds':()=>data.source==='pool'?post('/api/expenses',{date:data.date,category:page,description:data.note,amount:data.amount}):post('/api/goals/use',{date:data.date,goalId:data.source,note:data.note,amount:data.amount}),
      'new-goal':()=>post('/api/goals',{category:page,name:data.name,goalType:data.goalType,targetAmount:data.target}),
      'debt-payment':()=>post('/api/debt-payments',{date:data.date,debtId:data.debtId,amount:data.amount,note:data.note}),
      'add-debt':()=>post('/api/debts',{creditor:data.creditor,currentBalance:data.balance,dueDate:data.dueDate,paymentAmount:data.payment,paymentFrequency:'monthly',interestMode:data.interestMode,interestValue:data.interestValue,interestFrequency:data.frequency,interestBasis:'remaining',paused:data.status==='Paused'}),
      'update-debt':()=>post('/api/debts/agreement',{debtId:data.id,effectiveOn:data.date,dueDate:data.date,reason:data.reason,currentBalance:data.balance,paymentAmount:data.payment,paymentFrequency:'monthly',interestMode:data.interestMode,interestValue:data.interestValue,interestFrequency:data.frequency,interestBasis:'remaining',paused:data.status==='Paused'}),
      transfer:()=>post('/api/funds/transfer',{date:data.date,from:data.from,to:data.to,amount:data.amount}),
      allocations:()=>post('/api/allocation-rules',{effectiveFrom:phDate(),living:data.living,debt:data.debt,savings:data.savings,fun:data.fun}),
      'expected-income':()=>post('/api/expected-income',{expectedOn:data.date,name:data.name,source:data.source,amount:data.amount}),
      'receive-expected':()=>post('/api/expected-income/receive',{expectedIncomeId:data.id,date:data.date,amount:data.amount}),
      'bill-plan':async()=>{const plan=await post('/api/living-plans',{name:data.name,planType:'bill',plannedAmount:data.plan,dueDay:data.dueDay});await post('/api/living-bills',{planId:plan.id,billingMonth:phDate().slice(0,7),dueOn:billDate(phDate().slice(0,7),Number(data.dueDay)),actualAmount:data.actual});return plan;},
      'budget-plan':()=>post('/api/living-plans',{name:data.name,planType:'budget',plannedAmount:data.plan}),
      'recovery-goal':()=>post('/api/recovery/goal',{targetBalance:data.targetBalance,targetDate:data.targetDate}),
      'start-journey':()=>post('/api/recovery/start',{date:phDate()}),
      'delete-account':()=>post('/api/account/deletion',{confirmation:data.confirmation})
    };
    if(!routes[kind])throw new Error('This production action is not connected yet.');return routes[kind]();
  }
  async function bootstrap(){
    if(!live)return null;
    const [session,dash,expected,living,goals,debts,recovery,activity]=await Promise.all([request('/api/session'),request('/api/dashboard'),request('/api/expected-income'),request('/api/living-plans'),request('/api/goals'),request('/api/debts'),request('/api/recovery'),request('/api/activity?limit=100')]);
    const funds={living:0,debt:0,savings:0,fun:0};dash.balances.forEach(x=>{if(x.category in funds)funds[x.category]=Number(x.amount_minor)/100;});
    const mappedDebts=debts.items.map(mapDebt),mappedBills=living.items.filter(x=>x.plan_type==='bill').map(x=>{const actual=Number(x.actual_amount_minor??x.planned_amount_minor)/100,paid=Number(x.paid_amount_minor||0)/100;return {id:x.id,name:x.name,plan:x.planned_amount_minor/100,actual,dueDay:x.due_day,dueOn:x.due_on,status:x.bill_status==='paid'?'Paid':actual>x.planned_amount_minor/100?'Needs review':x.bill_status==='partially_paid'?'Partially paid':'Upcoming',paid};}),attention=[...mappedDebts.filter(x=>x.status==='Overdue').map(x=>['OVERDUE',x.creditor,'Debt payment overdue',x.payment]),...mappedBills.filter(x=>x.status==='Needs review').map(x=>['BILL NEEDS REVIEW',x.name,'Actual is above the monthly plan',Math.max(x.actual-x.plan,0)]),...Object.entries(funds).filter(([,value])=>value<0).map(([key,value])=>['ALLOCATION SHORTFALL',title(key),`New ${title(key)} allocation covers this first`,Math.abs(value)])].slice(0,6);
    const mappedActivity=activity.items.map(mapActivity),activeEntitlement=session.entitlements.find(x=>x.status==='active'&&x.ends_on>=phDate());
    const transferMap=new Map();activity.items.filter(x=>x.related_type==='transfer').forEach(x=>{const m=transferMap.get(x.related_id)||{id:x.related_id,date:x.occurred_on};if(x.entry_type==='transfer_out'){m.from=x.category;m.amount=Math.abs(Number(x.amount_minor))/100;}if(x.entry_type==='transfer_in')m.to=x.category;transferMap.set(x.related_id,m);});
    const patch={userRole:session.user.role,funds,attention,accountAccess:{status:activeEntitlement?'Active':'Inactive',plan:activeEntitlement?title(activeEntitlement.plan):'No active plan',endsOn:activeEntitlement?.ends_on||''},recoverySummary:{recoveredPercentage:recovery.recoveredPercentage,recoveredMinor:recovery.recoveredMinor/100,noNewDebtDays:recovery.noNewDebtDays,debtsCleared:recovery.debtsCleared.length},recoveryBreakdown:{payments:recovery.breakdown.paymentsMinor/100,negotiated:recovery.breakdown.negotiatedMinor/100,corrections:recovery.breakdown.correctionsMinor/100,interest:recovery.breakdown.interestMinor/100,newDebt:recovery.breakdown.newDebtMinor/100},allocations:dash.allocation?[['living','Living Expenses'],['debt','Debt'],['savings','Savings'],['fun','Fun']].map(([key,name])=>({key,name,percentage:Number(dash.allocation[`${key}_percentage`])})):undefined,incomes:activity.items.filter(x=>x.entry_type==='income').map(x=>({id:x.id,date:x.occurred_on,source:safeMeta(x).source||'Income',description:x.description,amount:x.amount_minor/100,allocated:true})),expected:expected.items.map(x=>({id:x.id,date:x.expected_on,name:x.name,source:x.source,amount:x.amount_minor/100,status:title(x.status)})),bills:mappedBills,budgets:living.items.filter(x=>x.plan_type==='budget').map(x=>({id:x.id,name:x.name,plan:x.planned_amount_minor/100,spent:Math.abs(activity.items.filter(a=>a.related_type==='living_plan'&&a.related_id===x.id&&a.entry_type==='expense').reduce((sum,a)=>sum+Number(a.amount_minor),0))/100})),goals:{savings:mapGoals(goals.items,'savings'),fun:mapGoals(goals.items,'fun')},debts:mappedDebts,recoveryPoints:recovery.snapshots.map(x=>({date:x.snapshot_on,balance:x.balance_minor/100})),activities:mappedActivity,transfers:[...transferMap.values()].filter(x=>x.from&&x.to)};
    patch.journey=recovery.journey?{startDate:recovery.journey.started_on,startingDebt:recovery.startingDebtMinor/100,targetBalance:recovery.journey.target_balance_minor/100,targetDate:recovery.journey.target_date||'',noNewDebtSince:recovery.journey.no_new_debt_since}:null;return patch;
  }
  function mapGoals(items,category){return items.filter(x=>x.category===category).map(x=>({id:x.id,name:x.name,type:x.goal_type,target:Number(x.target_amount_minor||0)/100,balance:Number(x.saved_minor||0)/100}));}
  function mapDebt(x){const due=x.agreement?.dueDate||'',status=x.status==='paused'?'Paused':x.status==='paid'?'Paid':due&&due<phDate()?'Overdue':'Upcoming';return {id:x.id,creditor:x.creditor_name,balance:x.current_balance_minor/100,starting:x.journey_start_balance_minor/100,payment:Number(x.agreement?.paymentAmountMinor||0)/100,dueDate:due,status,interestMode:x.agreement?.interestMode||'none',interestValue:Number(x.agreement?.interestValue||0),interestFrequency:x.agreement?.interestFrequency||'monthly',paused:Boolean(x.agreement?.paymentPaused),created:x.created_at?.slice(0,10)};}
  function mapActivity(x){const debtTypes=['interest','new_debt','negotiated_reduction','balance_correction'],category=debtTypes.includes(x.entry_type)?'debt':x.category,amount=x.entry_type==='goal_allocation'?Math.abs(Number(x.amount_minor))/100:x.entry_type==='goal_use'?-Math.abs(Number(x.amount_minor))/100:Number(x.amount_minor)/100,types={debt_payment:'payment',bill_payment:'bill',direct_funds:'funds',goal_allocation:'goal',goal_use:'withdrawal',negotiated_reduction:'negotiated',balance_correction:'correction',new_debt:'new-debt',transfer_in:'transfer',transfer_out:'transfer'};return {id:x.id,date:x.occurred_on,category,type:types[x.entry_type]||x.entry_type.replaceAll('_','-'),title:x.description,detail:'Recorded in your financial ledger',amount};}
  function safeMeta(x){try{return JSON.parse(x.metadata_json||'{}');}catch{return{};}}
  function title(v){return String(v||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}
  function phDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
  function billDate(month,day){const [year,number]=month.split('-').map(Number),last=new Date(Date.UTC(year,number,0)).getUTCDate();return `${month}-${String(Math.min(Math.max(day,1),last)).padStart(2,'0')}`;}
  function humanError(code,data){return ({authentication_required:'Please sign in.',access_required:'No active access was found for this Gmail.',admin_required:'Administrator access is required.',payment_received_access_pending:'Payment received—access setup is pending. You do not need to purchase again.',access_expired:'Your access has expired.',allocation_rule_required:'Set allocation percentages before recording income.',allocations_must_total_100:'Allocation percentages must total exactly 100%.',invalid_transfer:'Choose different source and destination categories and enter a valid amount.',invalid_goal_allocation:'Enter a valid goal allocation amount and date.',invalid_goal_use:'Enter a valid goal withdrawal amount and date.',insufficient_available_funds:'The selected category does not have enough available funds.',insufficient_goal_funds:'The selected goal does not have enough funds.',insufficient_category_funds:'The selected category does not have enough available funds.',insufficient_debt_funds:'Debt funds are not enough for this payment.',excess_payment_not_allowed:'This payment exceeds the current debt balance. Change the amount.',excess_bill_payment_not_allowed:'This payment exceeds the current unpaid bill amount.',no_unpaid_bill:'No unpaid current bill was found.',only_fully_paid_debt_can_be_archived:'Only a fully paid debt can be archived.'})[code]||'The request could not be completed. Please review the fields and try again.';}
  window.DRS_API={live,request,persist,bootstrap};
})();
